### ISSUE TITLE
-p, --pattern

### ISSUE THREAD

**Issue by miguelarauj1o** [miguelarauj1o/pmt#18]
A ferramenta também poderá receber um conjunto de padrões a serem procurados num arquivo, sendo um padrão por linha. Realiza a busca de todos os padrões contidos no arquivo _pattern- file_.

**Comment by paulolieuthier** [comment]
Já tá feito? https://github.com/miguelarauj1o/pmt/blob/master/src/search.h#L39

**Comment by miguelarauj1o** [comment]
véi.
