### ISSUE TITLE
[PENDING] Windows binary

### ISSUE THREAD

**Issue by sergeevabc** [miguelarauj1o/pmt#21]
Dear Miguel,
Could you be so kind to generate ```.exe``` for the rest of us who are merely users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by miguelarauj1o** [comment]
Sorry, but I can't help you right now.
I have been busy working on a project.
@paulolieuthier, can you help him?

**Comment by paulolieuthier** [comment]
@sergeevabc neither I or @miguelarauj1o use Windows, so it is not trivial to get this. I just commited a cross-compiled binary from Linux, for Win32. Test it and let me know if it doesn't work.

**Comment by sergeevabc** [comment]
Thanks.
It works, however extension should be changed to ```.exe```.
Also you could mention it in [readme.txt][1] or put to [Releases][2] for others to try.

[1]: https://github.com/miguelarauj1o/pmt/blob/master/README.txt
[2]: https://github.com/miguelarauj1o/pmt/releases

**Comment by sergeevabc** [comment]
Typo (“search”):
```
-v, --invert                  Invert serach
```

**Comment by paulolieuthier** [comment]
This was a project for a course at university, and we are no longer willing to maintain it. For curiosity, the `-v` flag was set for compatibility with grep. If you want to, send us pull requests to fix typos or bugs and improve documentation.

**Comment by sergeevabc** [comment]
Had user been able to polish reported roughness, he would be called a developer. Good luck, fellas.

**Comment by paulolieuthier** [comment]
I'm fine with givin you commit access, I'm sure Miguel is as well, would you like it?

**Comment by sergeevabc** [comment]
Thanks for invitation, but I’m merely a user (see first message) without skills to submit commits.
Since project is abandoned, consider stating it on front-page. Fortunately there are [pt][1], [ripgrep][2]. [sift][3], ugc[4].

[1]: https://github.com/monochromegane/the_platinum_searcher/
[2]: https://github.com/BurntSushi/ripgrep/
[3]: https://github.com/svent/sift/
[4]: https://github.com/gvansickle/ucg/
